version: "3.3"

services:
  slackbot-release:
    build:
      context: .
      dockerfile: Dockerfile
    image: grip/slackbot-release:latest
    container_name: slackbot-release
    restart: unless-stopped
    environment:
      - DOPPLER_TOKEN={{DOPPLER_TOKEN_AUTH}}
    # env_file:
    #   - .env
